name: WORKFLOW TEST

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Unzip assets
      run: unzip assets.zip -d assets/

    - name: List directory contents
      run: ls -la
